# Generated by Django 5.1.3 on 2024-12-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0002_article_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
